### ISSUE TITLE
Capability Level 3 - Resiliency

### ISSUE THREAD

**Issue by jsenko** [Apicurio/apicurio-registry-operator#34]
- [ ] Does your operator support backup of your operand?
- [ ] Does your operator support off cluster backup? e.g. to S3
- [ ] Does your operator support restore of your operand through a backup?
- [ ] Do you have documentation for how to backup and restore? Please provide a link.
- [ ] Does your operand have a Liveness probe?
- [ ] Does your operand have a Readiness probe which will fail if any aspect of the operand is not ready? e.g. if the connection to the database fails.
- [ ] Does your operand support scaling?
- [ ] Does your operand use a rolling deployment strategy?
- [ ] Does your operator create a PodDisruptionBudget resource for your operand pods?
- [ ] Does your operand have CPU requests and limits set?
