### ISSUE TITLE
Capability Level 4 - Deep Insights

### ISSUE THREAD

**Issue by jsenko** [Apicurio/apicurio-registry-operator#35]
- Monitoring
  - Operand exposes monitoring metrics
  - Operator exposes monitoring metrics
- Alerting
  - Operand send useful alerts
- Metering
  - Operator leverages Operator Framework Metering
- K8s Events
  - Custom Resources contain Custom K8s events

- [ ] Does your operand expose monitoring metrics?
- [ ] Does your operator expose monitoring metrics?
- [ ] Does your operator create alerts?
- [ ] Do you have SOPs for each alert?
- [ ] Does your operator create critical alerts when the service is down and warning alerts for all other alerts?
- [ ] Does your operator emit custom k8s events?
- [ ] Does your operator create dashboards to read your operand metrics?
- [ ] Does your operator integrate into Connected Customer Experience (CCX) for critical metrics

**Comment by jsenko** [comment]
Includes #22 #23 #24
